### ISSUE TITLE
"Add column" adds second element

### ISSUE THREAD

**Issue by fancyFranci** [joomla-projects/gsoc19_page-builder#17]
### Steps to reproduce the issue
Create a container and inside of it a grid. Click 'add column' in the grid and see that the grid has a new column and the container has a new empty element too.

![column-add-element-after](https://user-images.githubusercontent.com/9084265/61536000-e693a300-aa33-11e9-85bc-fe9b023ba24b.jpg)

### Expected result
After clicking 'add column' only one new column gets created in the grid.

### Actual result
Instead of creating only one column, an empty element gets also created in the parent of the grid, the container.

**Comment by bahl24** [comment]
@fancyFranci I've made an attempt to fix this and also moved the appending/pushing part to vuex so that we can keep track of the changes done to the elementArray (helps in debugging)
https://github.com/joomla-projects/gsoc19_page-builder/pull/13/commits/4c0d5e4290867d809b689ad94dab5a6d6be18221
