### ISSUE TITLE
Gap after resizing

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#19]
### Steps to reproduce the issue
- Add a grid column with at least 3 columns.
- Resize (make it smaller) the first element

### Expected result
All successors should fill in the gaps

### Actual result
Only the first element is filling up the gap

### Additional comments
![wrong-gap](https://user-images.githubusercontent.com/1229869/61542568-206ba600-aa42-11e9-93c6-38d380f71f67.gif)

**Comment by fancyFranci** [comment]
Other columns in the row are following now.

**Comment by bembelimen** [comment]
![grafik](https://user-images.githubusercontent.com/1229869/61939814-67065680-af94-11e9-8f75-3be2b282c7d6.png)
There are still gaps

Correct would be:
![grafik](https://user-images.githubusercontent.com/1229869/61940927-b3eb2c80-af96-11e9-8350-d6ef03ede00c.png)
3 + 1 + 1 + 1 + 2 < 12 => all in one line.
