### ISSUE TITLE
Disable vertical resize

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#20]
### Steps to reproduce the issue
- Add a grid
- Resize a colum vertical

### Expected result
Nothing should happen

### Actual result
Colum is resized, has animation and blocks space

### Additional comments
![vertical-resize](https://user-images.githubusercontent.com/1229869/61542770-835d3d00-aa42-11e9-87ef-d063553c3dba.gif)

**Comment by bahl24** [comment]
@bembelimen @fancyFranci kindly check

**Comment by fancyFranci** [comment]
I changed the icon, so the user thinks that only the size of a column can resize.
