### ISSUE TITLE
Drag&Drop broken

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#21]
### Steps to reproduce the issue
- Insert a grid with columns
- Drag&Drop the columns arround

### Expected result
- Sibling columns adjust and gaps will be filled

### Actual result
- see GIF

### Additional comments
![drag-n-drop](https://user-images.githubusercontent.com/1229869/61543171-3e85d600-aa43-11e9-94a3-2e383ed8576f.gif)

**Comment by bembelimen** [comment]
![page-builder-reorder](https://user-images.githubusercontent.com/1229869/61940815-856d5180-af96-11e9-8370-9af21fcba80e.gif)
Reordering is broken, too.

**Comment by anuragteapot** [comment]
@fancyFranci @bahl24 This issue is fixed, right ?

**Comment by bahl24** [comment]
@Anu1601CS Yes, this was fixed
