### ISSUE TITLE
Offset does not work

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#22]
### Steps to reproduce the issue
Try to add offset to a grid column element

### Expected result
- Only offsets which making sense are available (offset + elem size should not be greater than 12)

### Actual result
- Always all offsets are available

### Additional comments
![offset](https://user-images.githubusercontent.com/1229869/61544603-1ba8f100-aa46-11e9-85be-529c5c708559.gif)

**Comment by bahl24** [comment]
Has been completed
