### ISSUE TITLE
Rename modals "save" to "insert"

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#24]
### Steps to reproduce the issue
Insert an element

### Expected result
There is an "insert button"

### Actual result
button is called "save"

**Comment by fancyFranci** [comment]
Now the modal has an 'Insert' button.
![grafik](https://user-images.githubusercontent.com/9084265/61643933-1cd75980-aca4-11e9-8417-84651c70e989.png)
