### ISSUE TITLE
Remove grid size

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#25]
### Steps to reproduce the issue
Open template page builder

### Expected result
no grid size settings

### Actual result
![grafik](https://user-images.githubusercontent.com/1229869/61546975-befc0500-aa4a-11e9-8c59-760281b5436a.png)

**Comment by fancyFranci** [comment]
Now grid sizes can be found in the settings of each grid only.

**Comment by bembelimen** [comment]
Not needed at all, just hard code "12" for the default grid.

**Comment by fancyFranci** [comment]
Grid sizes removed entirely and replaced with hard coded '12'.
