### ISSUE TITLE
Column generated my add column button does not contain title in top left corner.

### ISSUE THREAD

**Issue by anuragteapot** [joomla-projects/gsoc19_page-builder#26]
### Steps to reproduce the issue
Add column using add column button.

### Expected result
Title column in top left the corner.

### Actual result
No title. 

![Screenshot from 2019-07-21 12-08-53](https://user-images.githubusercontent.com/30978328/61587925-cf2df480-abb0-11e9-8d92-bd633f88d442.png)

**Comment by bahl24** [comment]
I had fixed it recently, kindly check. You might have to clear the existing elements first as json structure has been modified
