### ISSUE TITLE
Add column overlaps other and color issue.

### ISSUE THREAD

**Issue by anuragteapot** [joomla-projects/gsoc19_page-builder#27]
### Steps to reproduce the issue
See gif

![chrome-capture](https://user-images.githubusercontent.com/30978328/61588382-26839300-abb8-11e9-8754-07e294023856.gif)

**Comment by fancyFranci** [comment]
Could you please describe the problem(s)? It is good to show a gif, but I don't understand what this one is telling us.

**Comment by anuragteapot** [comment]
@fancyFranci When you click on add column it adds a column but, that overlaps the other. It's difficult to see. 

Carefully see when to add column clicked and before and after.

**Comment by fancyFranci** [comment]
Yes, you're right, there was a problem with adding columns. It is fixed now and the new column gets a free place.
But I don't have this color issue. Maybe the css wasn't rebuild? Could you check again?

**Comment by bahl24** [comment]
running `node build.js --compile-css` will solve the color issue

**Comment by fancyFranci** [comment]
As it seems to be ok now, I'm closing this issue.
