### ISSUE TITLE
Adding module position

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/gsoc19_page-builder#28]
### Is your feature request related to a problem? Please describe.
Adding module positions does not work.

### Describe the solution you'd like
When adding a module position, I'd like to be asked for the name of the position (required). I also should be able to change the name in the settings.

Also the size of the added element is not correct:
![page-builder-module-position](https://user-images.githubusercontent.com/1229869/61941925-b51d5900-af98-11e9-8895-06d467832146.gif)

**Comment by bahl24** [comment]
Done
