### ISSUE TITLE
Add column button on the wrong position

### ISSUE THREAD

**Issue by drmenzelit** [joomla-projects/gsoc19_page-builder#30]
### Steps to reproduce the issue
Create a grid with columns and add a module position inside a column.

### Expected result
The columns adapt the size and the "add column" button shows below the columns as last element

### Actual result
The column with the module position is heigher than the others and the "add column" button overlaps

![2019-08-01 14_02_10-Templates_ Edit Style - GSoC - Administration](https://user-images.githubusercontent.com/9153168/62293987-2e6ded80-b46a-11e9-863b-22789ccaecda.jpg)

**Comment by fancyFranci** [comment]
This is fixed with a more stable solution. The [+] buttons moved to the upper right corner of every item, where they can not disturb anything.
![grafik](https://user-images.githubusercontent.com/9084265/62357759-0dfa6d80-b514-11e9-9738-c4548d8a71ba.png)
