### ISSUE TITLE
Layout is not bound to the selected device

### ISSUE THREAD

**Issue by drmenzelit** [joomla-projects/gsoc19_page-builder#31]
The layout should be attached to the selected device, e.g. the changes made on "desktop" should be only for this device. So will be possible to have responsive layouts.

**Comment by fancyFranci** [comment]
It is implemented and testable.

**Comment by fancyFranci** [comment]
As discussed, I will set that the editor takes the next smallest col- definition and not just col-x on missing col- definitions. Exactly like bootstrap is handling that.
