### ISSUE TITLE
Nice frontend rendering

### ISSUE THREAD

**Issue by bahl24** [joomla-projects/gsoc19_page-builder#33]
### Describe the solution you'd like
Fix frontend rendering, to correctly display all elements

**Comment by fancyFranci** [comment]
Could you please describe exactly what should get fixed and correctly displayed? Screenshots would be great. Because I have no idea what I could do for this issue :/

**Comment by bahl24** [comment]
One thing I can notice is that module pos along with module chrome is not being rendered correctly, other things the mentors can tell better

**Comment by drmenzelit** [comment]
It was not a fixing problem, but a feature request: please make the frontend nice :-)
