### ISSUE TITLE
New grid columns should relate to the currently selected device

### ISSUE THREAD

**Issue by fancyFranci** [joomla-projects/gsoc19_page-builder#43]
### Steps to reproduce the issue
Select the large device. Create a grid with some smaller columns. Change the device to a smaller one and look at the sizes of the columns.

### Expected result
The columns have their size only on the selected device and above. Smaller devices get the full grid size for these columns.

### Actual result
The columns have the same size for every device unless this gets changed manually.

**Comment by bahl24** [comment]
I have fixed this, kindly check
